### ISSUE TITLE
How to debug socket hang up error

### ISSUE THREAD

**Issue by git2g** [ibm-functions/runtime-nodejs#75]
Do you guys have any insight into what causes this `socket hang up` issue. Any debugging tips to figure out the root cause? 

```
2017-11-22T21:08:46.367732323Z stdout: name: 'OpenWhiskError',
2017-11-22T21:08:46.367745797Z stdout: message: 'Unknown Error From API: socket hang up',
2017-11-22T21:08:46.367755181Z stdout: error: undefined,
2017-11-22T21:08:46.367767686Z stdout: statusCode: undefined }
2017-11-22T21:08:46.370981901Z stderr: (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: actionName is not defined
2017-11-22T21:08:46.371852152Z stdout: { OpenWhiskError: Unknown Error From API: socket hang up
2017-11-22T21:08:46.371875835Z stdout: at Client.handle_errors (/nodejsAction/node_modules/openwhisk/lib/client.js:141:11)
2017-11-22T21:08:46.371886308Z stdout: at rp.catch.err (/nodejsAction/node_modules/openwhisk/lib/client.js:102:38)
2017-11-22T21:08:46.371895126Z stdout: name: 'OpenWhiskError',
2017-11-22T21:08:46.371902415Z stdout: message: 'Unknown Error From API: socket hang up',
2017-11-22T21:08:46.371910902Z stdout: error: undefined,
2017-11-22T21:08:46.371918849Z stdout: statusCode: undefined }
2017-11-22T21:08:46.372246665Z stderr: (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: actionName is not defined

```

**Comment by csantanapr** [comment]
Could you provide steps to reproduce.

From the errors I can only say, your code went thru a code path where you never called resolve or reject, and the rejected promised bubble to the globa context

**Comment by csantanapr** [comment]
By the way this repository is for IBM specific runtime, the Apache OpenWhiks node js runtime is located here: https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues

**Comment by csantanapr** [comment]
In terms of debugging nodejs I like to run the function locally in my computer passing the same parameters I expect, and using VSCode nodejs capabilities to do debugging like break points and such.

**Comment by csantanapr** [comment]
No steps were provided to reproduce, closing.
Probably didn't resolved or rejected the promise, or not defined main functions
