### ISSUE TITLE
CredentialsIBMNodeJsActionCloudantTests test does not pass reliably

### ISSUE THREAD

**Issue by dubeejw** [ibm-functions/runtime-nodejs#81]
There is a test from `CredentialsIBMNodeJsActionCloudantTests` that constantly fails. See failure below.

```
integration.CredentialsIBMNodeJsActionCloudantTests > should Test whether or not cloudant database is reachable using cloudant npm module STANDARD_OUT
    Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: error waiting for activation 7a169cdffcca4603969cdffccae603af: Cannot find activation id from 'null'

integration.CredentialsIBMNodeJsActionCloudantTests > should Test whether or not cloudant database is reachable using cloudant npm module FAILED
    org.scalatest.exceptions.TestFailedException: error waiting for activation 7a169cdffcca4603969cdffccae603af: Cannot find activation id from 'null'
        at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
        at org.scalatest.FlatSpec.newAssertionFailedException(FlatSpec.scala:1685)
        at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
        at common.WskTestHelpers$class.withActivation(WskTestHelpers.scala:227)
        at integration.CredentialsIBMNodeJsActionCloudantTests.withActivation(CredentialsIBMNodeJsActionCloudantTests.scala:29)
        at common.WskTestHelpers$class.withActivation(WskTestHelpers.scala:212)
        at integration.CredentialsIBMNodeJsActionCloudantTests.withActivation(CredentialsIBMNodeJsActionCloudantTests.scala:29)
        at integration.CredentialsIBMNodeJsActionCloudantTests$$anonfun$1$$anonfun$apply$1.apply(CredentialsIBMNodeJsActionCloudantTests.scala:50)
        at integration.CredentialsIBMNodeJsActionCloudantTests$$anonfun$1$$anonfun$apply$1.apply(CredentialsIBMNodeJsActionCloudantTests.scala:38)
        at common.WskTestHelpers$class.withAssetCleaner(WskTestHelpers.scala:162)
        at integration.CredentialsIBMNodeJsActionCloudantTests.withAssetCleaner(CredentialsIBMNodeJsActionCloudantTests.scala:29)
        at integration.CredentialsIBMNodeJsActionCloudantTests$$anonfun$1.apply(CredentialsIBMNodeJsActionCloudantTests.scala:37)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
        at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
        at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
        at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
        at integration.CredentialsIBMNodeJsActionCloudantTests.org$scalatest$BeforeAndAfterEachTestData$$super$runTest(CredentialsIBMNodeJsActionCloudantTests.scala:29)
        at org.scalatest.BeforeAndAfterEachTestData$class.runTest(BeforeAndAfterEachTestData.scala:194)
        at integration.CredentialsIBMNodeJsActionCloudantTests.runTest(CredentialsIBMNodeJsActionCloudantTests.scala:29)

```

**Comment by dubeejw** [comment]
@csantanapr, FYI.

**Comment by csantanapr** [comment]
@dubeejw should we increase the timeout?
The reason is not finding the activation record is because on indexing
```
error waiting for activation 7a169cdffcca4603969cdffccae603af
```

**Comment by csantanapr** [comment]
We have not seeing this recently
